
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed4;

	private global::Gtk.Button btmClickme;

	private global::Gtk.Label lblMainText;

	private global::Gtk.Entry Eingabe;

	private global::Gtk.Button button;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed4 = new global::Gtk.Fixed();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.btmClickme = new global::Gtk.Button();
		this.btmClickme.CanFocus = true;
		this.btmClickme.Name = "btmClickme";
		this.btmClickme.UseUnderline = true;
		this.btmClickme.Label = global::Mono.Unix.Catalog.GetString("Click Me");
		this.fixed4.Add(this.btmClickme);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.btmClickme]));
		w1.X = 279;
		w1.Y = 81;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.lblMainText = new global::Gtk.Label();
		this.lblMainText.Name = "lblMainText";
		this.fixed4.Add(this.lblMainText);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.lblMainText]));
		w2.X = 287;
		w2.Y = 174;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.Eingabe = new global::Gtk.Entry();
		this.Eingabe.CanFocus = true;
		this.Eingabe.Name = "Eingabe";
		this.Eingabe.IsEditable = true;
		this.Eingabe.InvisibleChar = '●';
		this.fixed4.Add(this.Eingabe);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.Eingabe]));
		w3.X = 104;
		w3.Y = 84;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.button = new global::Gtk.Button();
		this.button.CanFocus = true;
		this.button.Name = "button";
		this.button.UseUnderline = true;
		this.button.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.fixed4.Add(this.button);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.button]));
		w4.X = 296;
		w4.Y = 25;
		this.Add(this.fixed4);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 520;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btmClickme.Clicked += new global::System.EventHandler(this.ButtonClickMe_Clicked);
	}
}
