
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action DateiAction;

	private global::Gtk.Action BeendenAction;

	private global::Gtk.VBox layoutMenu_Input_Button;

	private global::Gtk.MenuBar menubar;

	private global::Gtk.HBox layoutInput_Output;

	private global::Gtk.VBox layoutInput;

	private global::Gtk.Table tblTroops;

	private global::Gtk.Button buttonTroopsSave;

	private global::Gtk.ComboBox cbxDriverTroops;

	private global::Gtk.ComboBox cbxHunterTroops;

	private global::Gtk.ComboBox cbxInfantryTroops;

	private global::Gtk.Entry entryDriverTroops;

	private global::Gtk.Entry entryHunterTroops;

	private global::Gtk.Entry entryInfantryTroops;

	private global::Gtk.Label lblDriverTroops;

	private global::Gtk.Label lblHunterTroops;

	private global::Gtk.Label lblInfantryTroops;

	private global::Gtk.Label lblTroops;

	private global::Gtk.HSeparator hzSeparator1;

	private global::Gtk.Table tblFormation;

	private global::Gtk.Entry entryDriverFormation;

	private global::Gtk.Entry entryHunterFormation;

	private global::Gtk.Entry entryInfantryFormation;

	private global::Gtk.Label lblDriverFormation;

	private global::Gtk.Label lblFormation;

	private global::Gtk.Label lblHunterFormation;

	private global::Gtk.Label lblInfantryFormation;

	private global::Gtk.Label lblMissingTroops;

	private global::Gtk.TextView textMissingDriv;

	private global::Gtk.TextView textMissingHun;

	private global::Gtk.TextView textMissingInf;

	private global::Gtk.HSeparator hzSeparator2;

	private global::Gtk.Table tblMarch;

	private global::Gtk.Entry entryCapacity;

	private global::Gtk.Entry entryPower;

	private global::Gtk.Label lblMarch;

	private global::Gtk.Label lblMarchCapacity;

	private global::Gtk.Label lblMarchPossible;

	private global::Gtk.Label lblMarchPower;

	private global::Gtk.HSeparator hzseparator3;

	private global::Gtk.HBox layoutRbnMarch;

	private global::Gtk.RadioButton rbnMarch1;

	private global::Gtk.RadioButton rbnMarch2;

	private global::Gtk.RadioButton rbnMarch3;

	private global::Gtk.HButtonBox buttonbox;

	private global::Gtk.Button buttonNextMarch;

	private global::Gtk.Button buttonChangeMarch;

	private global::Gtk.Button buttonReset;

	private global::Gtk.VSeparator vseparator3;

	private global::Gtk.Table layoutOutput;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.HSeparator hseparator3;

	private global::Gtk.HSeparator hseparator4;

	private global::Gtk.HSeparator hseparator5;

	private global::Gtk.Label lblMarch1;

	private global::Gtk.Label lblMarch2;

	private global::Gtk.Label lblMarch3;

	private global::Gtk.Label lblMarchCapa1;

	private global::Gtk.Label lblMarchCapa2;

	private global::Gtk.Label lblMarchCapa3;

	private global::Gtk.Label lblMarchDriv1;

	private global::Gtk.Label lblMarchDriv2;

	private global::Gtk.Label lblMarchDriv3;

	private global::Gtk.Label lblMarchForm1;

	private global::Gtk.Label lblMarchForm2;

	private global::Gtk.Label lblMarchForm3;

	private global::Gtk.Label lblMarchHun1;

	private global::Gtk.Label lblMarchHun2;

	private global::Gtk.Label lblMarchHun3;

	private global::Gtk.Label lblMarchInf1;

	private global::Gtk.Label lblMarchInf2;

	private global::Gtk.Label lblMarchInf3;

	private global::Gtk.Label lblMarchPow1;

	private global::Gtk.Label lblMarchPow2;

	private global::Gtk.Label lblMarchPow3;

	private global::Gtk.TextView textMarchCapa1;

	private global::Gtk.TextView textMarchCapa2;

	private global::Gtk.TextView textMarchCapa3;

	private global::Gtk.TextView textMarchDriv1;

	private global::Gtk.TextView textMarchDriv2;

	private global::Gtk.TextView textMarchDriv3;

	private global::Gtk.TextView textMarchForm1;

	private global::Gtk.TextView textMarchForm2;

	private global::Gtk.TextView textMarchForm3;

	private global::Gtk.TextView textMarchHun1;

	private global::Gtk.TextView textMarchHun2;

	private global::Gtk.TextView textMarchHun3;

	private global::Gtk.TextView textMarchInf1;

	private global::Gtk.TextView textMarchInf2;

	private global::Gtk.TextView textMarchInf3;

	private global::Gtk.TextView textMarchPow1;

	private global::Gtk.TextView textMarchPow2;

	private global::Gtk.TextView textMarchPow3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.DateiAction = new global::Gtk.Action("DateiAction", global::Mono.Unix.Catalog.GetString("Datei"), null, null);
		this.DateiAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Datei");
		w1.Add(this.DateiAction, null);
		this.BeendenAction = new global::Gtk.Action("BeendenAction", global::Mono.Unix.Catalog.GetString("Beenden"), null, null);
		this.BeendenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Beenden");
		w1.Add(this.BeendenAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Truppenrechner");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.layoutMenu_Input_Button = new global::Gtk.VBox();
		this.layoutMenu_Input_Button.Name = "layoutMenu_Input_Button";
		this.layoutMenu_Input_Button.Spacing = 6;
		// Container child layoutMenu_Input_Button.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar\'><menu/><menu name=\'DateiAction\' action=\'DateiAction\'>" +
				"<menuitem name=\'BeendenAction\' action=\'BeendenAction\'/></menu></menubar></ui>");
		this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar")));
		this.menubar.Name = "menubar";
		this.layoutMenu_Input_Button.Add(this.menubar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.layoutMenu_Input_Button[this.menubar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child layoutMenu_Input_Button.Gtk.Box+BoxChild
		this.layoutInput_Output = new global::Gtk.HBox();
		this.layoutInput_Output.Name = "layoutInput_Output";
		this.layoutInput_Output.Spacing = 6;
		// Container child layoutInput_Output.Gtk.Box+BoxChild
		this.layoutInput = new global::Gtk.VBox();
		this.layoutInput.Name = "layoutInput";
		this.layoutInput.Spacing = 6;
		// Container child layoutInput.Gtk.Box+BoxChild
		this.tblTroops = new global::Gtk.Table(((uint)(4)), ((uint)(3)), true);
		this.tblTroops.Name = "tblTroops";
		this.tblTroops.RowSpacing = ((uint)(6));
		this.tblTroops.ColumnSpacing = ((uint)(6));
		// Container child tblTroops.Gtk.Table+TableChild
		this.buttonTroopsSave = new global::Gtk.Button();
		this.buttonTroopsSave.CanFocus = true;
		this.buttonTroopsSave.Name = "buttonTroopsSave";
		this.buttonTroopsSave.UseUnderline = true;
		this.buttonTroopsSave.Label = global::Mono.Unix.Catalog.GetString("Truppen speichern");
		this.tblTroops.Add(this.buttonTroopsSave);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.buttonTroopsSave]));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.cbxDriverTroops = global::Gtk.ComboBox.NewText();
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T1"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T2"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T3"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T4"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T5"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T6"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T7"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T8"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T9"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10*"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10**"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10***"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10****"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10*****"));
		this.cbxDriverTroops.AppendText(global::Mono.Unix.Catalog.GetString("T11"));
		this.cbxDriverTroops.Name = "cbxDriverTroops";
		this.cbxDriverTroops.Active = 0;
		this.tblTroops.Add(this.cbxDriverTroops);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.cbxDriverTroops]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.LeftAttach = ((uint)(2));
		w4.RightAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.cbxHunterTroops = global::Gtk.ComboBox.NewText();
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T1"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T2"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T3"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T4"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T5"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T6"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T7"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T8"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T9"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10*"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10**"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10***"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10****"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10*****"));
		this.cbxHunterTroops.AppendText(global::Mono.Unix.Catalog.GetString("T11"));
		this.cbxHunterTroops.Name = "cbxHunterTroops";
		this.cbxHunterTroops.Active = 0;
		this.tblTroops.Add(this.cbxHunterTroops);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.cbxHunterTroops]));
		w5.TopAttach = ((uint)(3));
		w5.BottomAttach = ((uint)(4));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.cbxInfantryTroops = global::Gtk.ComboBox.NewText();
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T1"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T2"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T3"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T4"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T5"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T6"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T7"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T8"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T9"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10*"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10**"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10***"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10****"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T10*****"));
		this.cbxInfantryTroops.AppendText(global::Mono.Unix.Catalog.GetString("T11"));
		this.cbxInfantryTroops.Name = "cbxInfantryTroops";
		this.cbxInfantryTroops.Active = 0;
		this.tblTroops.Add(this.cbxInfantryTroops);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.cbxInfantryTroops]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(2));
		w6.RightAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.entryDriverTroops = new global::Gtk.Entry();
		this.entryDriverTroops.CanFocus = true;
		this.entryDriverTroops.Name = "entryDriverTroops";
		this.entryDriverTroops.IsEditable = true;
		this.entryDriverTroops.InvisibleChar = '●';
		this.tblTroops.Add(this.entryDriverTroops);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.entryDriverTroops]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.entryHunterTroops = new global::Gtk.Entry();
		this.entryHunterTroops.CanFocus = true;
		this.entryHunterTroops.Name = "entryHunterTroops";
		this.entryHunterTroops.IsEditable = true;
		this.entryHunterTroops.InvisibleChar = '●';
		this.tblTroops.Add(this.entryHunterTroops);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.entryHunterTroops]));
		w8.TopAttach = ((uint)(3));
		w8.BottomAttach = ((uint)(4));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.entryInfantryTroops = new global::Gtk.Entry();
		this.entryInfantryTroops.CanFocus = true;
		this.entryInfantryTroops.Name = "entryInfantryTroops";
		this.entryInfantryTroops.IsEditable = true;
		this.entryInfantryTroops.InvisibleChar = '●';
		this.tblTroops.Add(this.entryInfantryTroops);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.entryInfantryTroops]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.lblDriverTroops = new global::Gtk.Label();
		this.lblDriverTroops.Name = "lblDriverTroops";
		this.lblDriverTroops.Xalign = 1F;
		this.lblDriverTroops.LabelProp = global::Mono.Unix.Catalog.GetString("Fahrer:");
		this.tblTroops.Add(this.lblDriverTroops);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.lblDriverTroops]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.lblHunterTroops = new global::Gtk.Label();
		this.lblHunterTroops.Name = "lblHunterTroops";
		this.lblHunterTroops.Xalign = 1F;
		this.lblHunterTroops.LabelProp = global::Mono.Unix.Catalog.GetString("Jäger:");
		this.tblTroops.Add(this.lblHunterTroops);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.lblHunterTroops]));
		w11.TopAttach = ((uint)(3));
		w11.BottomAttach = ((uint)(4));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.lblInfantryTroops = new global::Gtk.Label();
		this.lblInfantryTroops.Name = "lblInfantryTroops";
		this.lblInfantryTroops.Xalign = 1F;
		this.lblInfantryTroops.LabelProp = global::Mono.Unix.Catalog.GetString("Infanterie:");
		this.tblTroops.Add(this.lblInfantryTroops);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.lblInfantryTroops]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTroops.Gtk.Table+TableChild
		this.lblTroops = new global::Gtk.Label();
		this.lblTroops.Name = "lblTroops";
		this.lblTroops.LabelProp = global::Mono.Unix.Catalog.GetString("Truppen");
		this.tblTroops.Add(this.lblTroops);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblTroops[this.lblTroops]));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		this.layoutInput.Add(this.tblTroops);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.layoutInput[this.tblTroops]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child layoutInput.Gtk.Box+BoxChild
		this.hzSeparator1 = new global::Gtk.HSeparator();
		this.hzSeparator1.Name = "hzSeparator1";
		this.layoutInput.Add(this.hzSeparator1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.layoutInput[this.hzSeparator1]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child layoutInput.Gtk.Box+BoxChild
		this.tblFormation = new global::Gtk.Table(((uint)(4)), ((uint)(3)), true);
		this.tblFormation.Name = "tblFormation";
		this.tblFormation.RowSpacing = ((uint)(6));
		this.tblFormation.ColumnSpacing = ((uint)(6));
		// Container child tblFormation.Gtk.Table+TableChild
		this.entryDriverFormation = new global::Gtk.Entry();
		this.entryDriverFormation.CanFocus = true;
		this.entryDriverFormation.Name = "entryDriverFormation";
		this.entryDriverFormation.IsEditable = true;
		this.entryDriverFormation.InvisibleChar = '●';
		this.tblFormation.Add(this.entryDriverFormation);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.entryDriverFormation]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.entryHunterFormation = new global::Gtk.Entry();
		this.entryHunterFormation.CanFocus = true;
		this.entryHunterFormation.Name = "entryHunterFormation";
		this.entryHunterFormation.IsEditable = true;
		this.entryHunterFormation.InvisibleChar = '●';
		this.tblFormation.Add(this.entryHunterFormation);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.entryHunterFormation]));
		w17.TopAttach = ((uint)(3));
		w17.BottomAttach = ((uint)(4));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.entryInfantryFormation = new global::Gtk.Entry();
		this.entryInfantryFormation.CanFocus = true;
		this.entryInfantryFormation.Name = "entryInfantryFormation";
		this.entryInfantryFormation.IsEditable = true;
		this.entryInfantryFormation.InvisibleChar = '●';
		this.tblFormation.Add(this.entryInfantryFormation);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.entryInfantryFormation]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.lblDriverFormation = new global::Gtk.Label();
		this.lblDriverFormation.Name = "lblDriverFormation";
		this.lblDriverFormation.Xalign = 1F;
		this.lblDriverFormation.LabelProp = global::Mono.Unix.Catalog.GetString("Fahrer:");
		this.tblFormation.Add(this.lblDriverFormation);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.lblDriverFormation]));
		w19.TopAttach = ((uint)(2));
		w19.BottomAttach = ((uint)(3));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.lblFormation = new global::Gtk.Label();
		this.lblFormation.Name = "lblFormation";
		this.lblFormation.LabelProp = global::Mono.Unix.Catalog.GetString("Formation (in %)");
		this.tblFormation.Add(this.lblFormation);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.lblFormation]));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.lblHunterFormation = new global::Gtk.Label();
		this.lblHunterFormation.Name = "lblHunterFormation";
		this.lblHunterFormation.Xalign = 1F;
		this.lblHunterFormation.LabelProp = global::Mono.Unix.Catalog.GetString("Jäger:");
		this.tblFormation.Add(this.lblHunterFormation);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.lblHunterFormation]));
		w21.TopAttach = ((uint)(3));
		w21.BottomAttach = ((uint)(4));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.lblInfantryFormation = new global::Gtk.Label();
		this.lblInfantryFormation.Name = "lblInfantryFormation";
		this.lblInfantryFormation.Xalign = 1F;
		this.lblInfantryFormation.LabelProp = global::Mono.Unix.Catalog.GetString("Infanterie:");
		this.tblFormation.Add(this.lblInfantryFormation);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.lblInfantryFormation]));
		w22.TopAttach = ((uint)(1));
		w22.BottomAttach = ((uint)(2));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.lblMissingTroops = new global::Gtk.Label();
		this.lblMissingTroops.Name = "lblMissingTroops";
		this.lblMissingTroops.LabelProp = global::Mono.Unix.Catalog.GetString("Fehlende Truppen");
		this.tblFormation.Add(this.lblMissingTroops);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.lblMissingTroops]));
		w23.LeftAttach = ((uint)(2));
		w23.RightAttach = ((uint)(3));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.textMissingDriv = new global::Gtk.TextView();
		this.textMissingDriv.Sensitive = false;
		this.textMissingDriv.Name = "textMissingDriv";
		this.textMissingDriv.Editable = false;
		this.textMissingDriv.CursorVisible = false;
		this.textMissingDriv.AcceptsTab = false;
		this.textMissingDriv.Justification = ((global::Gtk.Justification)(2));
		this.tblFormation.Add(this.textMissingDriv);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.textMissingDriv]));
		w24.TopAttach = ((uint)(2));
		w24.BottomAttach = ((uint)(3));
		w24.LeftAttach = ((uint)(2));
		w24.RightAttach = ((uint)(3));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.textMissingHun = new global::Gtk.TextView();
		this.textMissingHun.Sensitive = false;
		this.textMissingHun.Name = "textMissingHun";
		this.textMissingHun.Editable = false;
		this.textMissingHun.CursorVisible = false;
		this.textMissingHun.AcceptsTab = false;
		this.textMissingHun.Justification = ((global::Gtk.Justification)(2));
		this.tblFormation.Add(this.textMissingHun);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.textMissingHun]));
		w25.TopAttach = ((uint)(3));
		w25.BottomAttach = ((uint)(4));
		w25.LeftAttach = ((uint)(2));
		w25.RightAttach = ((uint)(3));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblFormation.Gtk.Table+TableChild
		this.textMissingInf = new global::Gtk.TextView();
		this.textMissingInf.Sensitive = false;
		this.textMissingInf.Name = "textMissingInf";
		this.textMissingInf.Editable = false;
		this.textMissingInf.CursorVisible = false;
		this.textMissingInf.AcceptsTab = false;
		this.textMissingInf.Justification = ((global::Gtk.Justification)(2));
		this.tblFormation.Add(this.textMissingInf);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.tblFormation[this.textMissingInf]));
		w26.TopAttach = ((uint)(1));
		w26.BottomAttach = ((uint)(2));
		w26.LeftAttach = ((uint)(2));
		w26.RightAttach = ((uint)(3));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		this.layoutInput.Add(this.tblFormation);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.layoutInput[this.tblFormation]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		// Container child layoutInput.Gtk.Box+BoxChild
		this.hzSeparator2 = new global::Gtk.HSeparator();
		this.hzSeparator2.Name = "hzSeparator2";
		this.layoutInput.Add(this.hzSeparator2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.layoutInput[this.hzSeparator2]));
		w28.Position = 3;
		w28.Expand = false;
		w28.Fill = false;
		// Container child layoutInput.Gtk.Box+BoxChild
		this.tblMarch = new global::Gtk.Table(((uint)(3)), ((uint)(3)), true);
		this.tblMarch.Name = "tblMarch";
		this.tblMarch.RowSpacing = ((uint)(6));
		this.tblMarch.ColumnSpacing = ((uint)(6));
		// Container child tblMarch.Gtk.Table+TableChild
		this.entryCapacity = new global::Gtk.Entry();
		this.entryCapacity.CanFocus = true;
		this.entryCapacity.Name = "entryCapacity";
		this.entryCapacity.IsEditable = true;
		this.entryCapacity.InvisibleChar = '●';
		this.tblMarch.Add(this.entryCapacity);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.tblMarch[this.entryCapacity]));
		w29.TopAttach = ((uint)(1));
		w29.BottomAttach = ((uint)(2));
		w29.LeftAttach = ((uint)(1));
		w29.RightAttach = ((uint)(2));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblMarch.Gtk.Table+TableChild
		this.entryPower = new global::Gtk.Entry();
		this.entryPower.CanFocus = true;
		this.entryPower.Name = "entryPower";
		this.entryPower.IsEditable = true;
		this.entryPower.InvisibleChar = '●';
		this.tblMarch.Add(this.entryPower);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.tblMarch[this.entryPower]));
		w30.TopAttach = ((uint)(2));
		w30.BottomAttach = ((uint)(3));
		w30.LeftAttach = ((uint)(1));
		w30.RightAttach = ((uint)(2));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblMarch.Gtk.Table+TableChild
		this.lblMarch = new global::Gtk.Label();
		this.lblMarch.Name = "lblMarch";
		this.lblMarch.LabelProp = global::Mono.Unix.Catalog.GetString("Marscheigenschaften");
		this.tblMarch.Add(this.lblMarch);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.tblMarch[this.lblMarch]));
		w31.LeftAttach = ((uint)(1));
		w31.RightAttach = ((uint)(2));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblMarch.Gtk.Table+TableChild
		this.lblMarchCapacity = new global::Gtk.Label();
		this.lblMarchCapacity.Name = "lblMarchCapacity";
		this.lblMarchCapacity.Xalign = 1F;
		this.lblMarchCapacity.LabelProp = global::Mono.Unix.Catalog.GetString("Marschkapazität:");
		this.tblMarch.Add(this.lblMarchCapacity);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.tblMarch[this.lblMarchCapacity]));
		w32.TopAttach = ((uint)(1));
		w32.BottomAttach = ((uint)(2));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblMarch.Gtk.Table+TableChild
		this.lblMarchPossible = new global::Gtk.Label();
		this.lblMarchPossible.Name = "lblMarchPossible";
		this.lblMarchPossible.LabelProp = global::Mono.Unix.Catalog.GetString("(X mögliche Märsche)");
		this.tblMarch.Add(this.lblMarchPossible);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.tblMarch[this.lblMarchPossible]));
		w33.TopAttach = ((uint)(1));
		w33.BottomAttach = ((uint)(2));
		w33.LeftAttach = ((uint)(2));
		w33.RightAttach = ((uint)(3));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblMarch.Gtk.Table+TableChild
		this.lblMarchPower = new global::Gtk.Label();
		this.lblMarchPower.Name = "lblMarchPower";
		this.lblMarchPower.Xalign = 1F;
		this.lblMarchPower.LabelProp = global::Mono.Unix.Catalog.GetString("Marschstärke:");
		this.tblMarch.Add(this.lblMarchPower);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.tblMarch[this.lblMarchPower]));
		w34.TopAttach = ((uint)(2));
		w34.BottomAttach = ((uint)(3));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		this.layoutInput.Add(this.tblMarch);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.layoutInput[this.tblMarch]));
		w35.Position = 4;
		w35.Expand = false;
		w35.Fill = false;
		// Container child layoutInput.Gtk.Box+BoxChild
		this.hzseparator3 = new global::Gtk.HSeparator();
		this.hzseparator3.Name = "hzseparator3";
		this.layoutInput.Add(this.hzseparator3);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.layoutInput[this.hzseparator3]));
		w36.Position = 5;
		w36.Expand = false;
		w36.Fill = false;
		// Container child layoutInput.Gtk.Box+BoxChild
		this.layoutRbnMarch = new global::Gtk.HBox();
		this.layoutRbnMarch.Name = "layoutRbnMarch";
		this.layoutRbnMarch.Spacing = 6;
		// Container child layoutRbnMarch.Gtk.Box+BoxChild
		this.rbnMarch1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Marsch 1"));
		this.rbnMarch1.CanFocus = true;
		this.rbnMarch1.Name = "rbnMarch1";
		this.rbnMarch1.DrawIndicator = true;
		this.rbnMarch1.UseUnderline = true;
		this.rbnMarch1.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.layoutRbnMarch.Add(this.rbnMarch1);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.layoutRbnMarch[this.rbnMarch1]));
		w37.Position = 0;
		// Container child layoutRbnMarch.Gtk.Box+BoxChild
		this.rbnMarch2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Marsch 2"));
		this.rbnMarch2.CanFocus = true;
		this.rbnMarch2.Name = "rbnMarch2";
		this.rbnMarch2.DrawIndicator = true;
		this.rbnMarch2.UseUnderline = true;
		this.rbnMarch2.Group = this.rbnMarch1.Group;
		this.layoutRbnMarch.Add(this.rbnMarch2);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.layoutRbnMarch[this.rbnMarch2]));
		w38.Position = 1;
		// Container child layoutRbnMarch.Gtk.Box+BoxChild
		this.rbnMarch3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Marsch 3"));
		this.rbnMarch3.CanFocus = true;
		this.rbnMarch3.Name = "rbnMarch3";
		this.rbnMarch3.DrawIndicator = true;
		this.rbnMarch3.UseUnderline = true;
		this.rbnMarch3.Group = this.rbnMarch1.Group;
		this.layoutRbnMarch.Add(this.rbnMarch3);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.layoutRbnMarch[this.rbnMarch3]));
		w39.Position = 2;
		this.layoutInput.Add(this.layoutRbnMarch);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.layoutInput[this.layoutRbnMarch]));
		w40.Position = 6;
		w40.Expand = false;
		w40.Fill = false;
		// Container child layoutInput.Gtk.Box+BoxChild
		this.buttonbox = new global::Gtk.HButtonBox();
		this.buttonbox.Name = "buttonbox";
		this.buttonbox.Homogeneous = true;
		this.buttonbox.BorderWidth = ((uint)(6));
		// Container child buttonbox.Gtk.ButtonBox+ButtonBoxChild
		this.buttonNextMarch = new global::Gtk.Button();
		this.buttonNextMarch.CanFocus = true;
		this.buttonNextMarch.Name = "buttonNextMarch";
		this.buttonNextMarch.UseUnderline = true;
		this.buttonNextMarch.Label = global::Mono.Unix.Catalog.GetString("Marsch berechnen");
		this.buttonbox.Add(this.buttonNextMarch);
		global::Gtk.ButtonBox.ButtonBoxChild w41 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonbox[this.buttonNextMarch]));
		w41.Expand = false;
		w41.Fill = false;
		// Container child buttonbox.Gtk.ButtonBox+ButtonBoxChild
		this.buttonChangeMarch = new global::Gtk.Button();
		this.buttonChangeMarch.CanFocus = true;
		this.buttonChangeMarch.Name = "buttonChangeMarch";
		this.buttonChangeMarch.UseUnderline = true;
		this.buttonChangeMarch.Label = global::Mono.Unix.Catalog.GetString("Marsch bearbeiten");
		this.buttonbox.Add(this.buttonChangeMarch);
		global::Gtk.ButtonBox.ButtonBoxChild w42 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonbox[this.buttonChangeMarch]));
		w42.Position = 1;
		w42.Expand = false;
		w42.Fill = false;
		// Container child buttonbox.Gtk.ButtonBox+ButtonBoxChild
		this.buttonReset = new global::Gtk.Button();
		this.buttonReset.CanFocus = true;
		this.buttonReset.Name = "buttonReset";
		this.buttonReset.UseUnderline = true;
		this.buttonReset.Label = global::Mono.Unix.Catalog.GetString("Reset");
		this.buttonbox.Add(this.buttonReset);
		global::Gtk.ButtonBox.ButtonBoxChild w43 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonbox[this.buttonReset]));
		w43.Position = 2;
		w43.Expand = false;
		w43.Fill = false;
		this.layoutInput.Add(this.buttonbox);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.layoutInput[this.buttonbox]));
		w44.Position = 7;
		w44.Expand = false;
		w44.Fill = false;
		this.layoutInput_Output.Add(this.layoutInput);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.layoutInput_Output[this.layoutInput]));
		w45.Position = 0;
		// Container child layoutInput_Output.Gtk.Box+BoxChild
		this.vseparator3 = new global::Gtk.VSeparator();
		this.vseparator3.Name = "vseparator3";
		this.layoutInput_Output.Add(this.vseparator3);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.layoutInput_Output[this.vseparator3]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		// Container child layoutInput_Output.Gtk.Box+BoxChild
		this.layoutOutput = new global::Gtk.Table(((uint)(23)), ((uint)(2)), false);
		this.layoutOutput.Name = "layoutOutput";
		this.layoutOutput.RowSpacing = ((uint)(6));
		this.layoutOutput.ColumnSpacing = ((uint)(6));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.layoutOutput.Add(this.hseparator1);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.hseparator1]));
		w47.TopAttach = ((uint)(7));
		w47.BottomAttach = ((uint)(8));
		w47.XOptions = ((global::Gtk.AttachOptions)(4));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.Name = "hseparator3";
		this.layoutOutput.Add(this.hseparator3);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.hseparator3]));
		w48.TopAttach = ((uint)(7));
		w48.BottomAttach = ((uint)(8));
		w48.LeftAttach = ((uint)(1));
		w48.RightAttach = ((uint)(2));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.hseparator4 = new global::Gtk.HSeparator();
		this.hseparator4.Name = "hseparator4";
		this.layoutOutput.Add(this.hseparator4);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.hseparator4]));
		w49.TopAttach = ((uint)(15));
		w49.BottomAttach = ((uint)(16));
		w49.XOptions = ((global::Gtk.AttachOptions)(4));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.hseparator5 = new global::Gtk.HSeparator();
		this.hseparator5.Name = "hseparator5";
		this.layoutOutput.Add(this.hseparator5);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.hseparator5]));
		w50.TopAttach = ((uint)(15));
		w50.BottomAttach = ((uint)(16));
		w50.LeftAttach = ((uint)(1));
		w50.RightAttach = ((uint)(2));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarch1 = new global::Gtk.Label();
		this.lblMarch1.Name = "lblMarch1";
		this.lblMarch1.LabelProp = global::Mono.Unix.Catalog.GetString("Marsch 1");
		this.layoutOutput.Add(this.lblMarch1);
		global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarch1]));
		w51.XOptions = ((global::Gtk.AttachOptions)(4));
		w51.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarch2 = new global::Gtk.Label();
		this.lblMarch2.Name = "lblMarch2";
		this.lblMarch2.LabelProp = global::Mono.Unix.Catalog.GetString("Marsch 2");
		this.layoutOutput.Add(this.lblMarch2);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarch2]));
		w52.TopAttach = ((uint)(8));
		w52.BottomAttach = ((uint)(9));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarch3 = new global::Gtk.Label();
		this.lblMarch3.Name = "lblMarch3";
		this.lblMarch3.LabelProp = global::Mono.Unix.Catalog.GetString("Marsch 3");
		this.layoutOutput.Add(this.lblMarch3);
		global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarch3]));
		w53.TopAttach = ((uint)(16));
		w53.BottomAttach = ((uint)(17));
		w53.XOptions = ((global::Gtk.AttachOptions)(4));
		w53.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchCapa1 = new global::Gtk.Label();
		this.lblMarchCapa1.Name = "lblMarchCapa1";
		this.lblMarchCapa1.Xalign = 0F;
		this.lblMarchCapa1.LabelProp = global::Mono.Unix.Catalog.GetString("Kapazität:");
		this.lblMarchCapa1.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchCapa1);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchCapa1]));
		w54.TopAttach = ((uint)(2));
		w54.BottomAttach = ((uint)(3));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchCapa2 = new global::Gtk.Label();
		this.lblMarchCapa2.Name = "lblMarchCapa2";
		this.lblMarchCapa2.Xalign = 0F;
		this.lblMarchCapa2.LabelProp = global::Mono.Unix.Catalog.GetString("Kapazität:");
		this.lblMarchCapa2.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchCapa2);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchCapa2]));
		w55.TopAttach = ((uint)(10));
		w55.BottomAttach = ((uint)(11));
		w55.XOptions = ((global::Gtk.AttachOptions)(4));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchCapa3 = new global::Gtk.Label();
		this.lblMarchCapa3.Name = "lblMarchCapa3";
		this.lblMarchCapa3.Xalign = 0F;
		this.lblMarchCapa3.LabelProp = global::Mono.Unix.Catalog.GetString("Kapazität:");
		this.lblMarchCapa3.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchCapa3);
		global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchCapa3]));
		w56.TopAttach = ((uint)(18));
		w56.BottomAttach = ((uint)(19));
		w56.XOptions = ((global::Gtk.AttachOptions)(4));
		w56.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchDriv1 = new global::Gtk.Label();
		this.lblMarchDriv1.Name = "lblMarchDriv1";
		this.lblMarchDriv1.Xalign = 0F;
		this.lblMarchDriv1.LabelProp = global::Mono.Unix.Catalog.GetString("Fahrer:");
		this.lblMarchDriv1.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchDriv1);
		global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchDriv1]));
		w57.TopAttach = ((uint)(5));
		w57.BottomAttach = ((uint)(6));
		w57.XOptions = ((global::Gtk.AttachOptions)(4));
		w57.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchDriv2 = new global::Gtk.Label();
		this.lblMarchDriv2.Name = "lblMarchDriv2";
		this.lblMarchDriv2.Xalign = 0F;
		this.lblMarchDriv2.LabelProp = global::Mono.Unix.Catalog.GetString("Fahrer:");
		this.lblMarchDriv2.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchDriv2);
		global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchDriv2]));
		w58.TopAttach = ((uint)(13));
		w58.BottomAttach = ((uint)(14));
		w58.XOptions = ((global::Gtk.AttachOptions)(4));
		w58.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchDriv3 = new global::Gtk.Label();
		this.lblMarchDriv3.Name = "lblMarchDriv3";
		this.lblMarchDriv3.Xalign = 0F;
		this.lblMarchDriv3.LabelProp = global::Mono.Unix.Catalog.GetString("Fahrer:");
		this.lblMarchDriv3.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchDriv3);
		global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchDriv3]));
		w59.TopAttach = ((uint)(21));
		w59.BottomAttach = ((uint)(22));
		w59.XOptions = ((global::Gtk.AttachOptions)(4));
		w59.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchForm1 = new global::Gtk.Label();
		this.lblMarchForm1.Name = "lblMarchForm1";
		this.lblMarchForm1.Xalign = 0F;
		this.lblMarchForm1.LabelProp = global::Mono.Unix.Catalog.GetString("Formation:");
		this.lblMarchForm1.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchForm1);
		global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchForm1]));
		w60.TopAttach = ((uint)(3));
		w60.BottomAttach = ((uint)(4));
		w60.XOptions = ((global::Gtk.AttachOptions)(4));
		w60.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchForm2 = new global::Gtk.Label();
		this.lblMarchForm2.Name = "lblMarchForm2";
		this.lblMarchForm2.Xalign = 0F;
		this.lblMarchForm2.LabelProp = global::Mono.Unix.Catalog.GetString("Formation:");
		this.lblMarchForm2.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchForm2);
		global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchForm2]));
		w61.TopAttach = ((uint)(11));
		w61.BottomAttach = ((uint)(12));
		w61.XOptions = ((global::Gtk.AttachOptions)(4));
		w61.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchForm3 = new global::Gtk.Label();
		this.lblMarchForm3.Name = "lblMarchForm3";
		this.lblMarchForm3.Xalign = 0F;
		this.lblMarchForm3.LabelProp = global::Mono.Unix.Catalog.GetString("Formation:");
		this.lblMarchForm3.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchForm3);
		global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchForm3]));
		w62.TopAttach = ((uint)(19));
		w62.BottomAttach = ((uint)(20));
		w62.XOptions = ((global::Gtk.AttachOptions)(4));
		w62.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchHun1 = new global::Gtk.Label();
		this.lblMarchHun1.Name = "lblMarchHun1";
		this.lblMarchHun1.Xalign = 0F;
		this.lblMarchHun1.LabelProp = global::Mono.Unix.Catalog.GetString("Jäger:");
		this.lblMarchHun1.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchHun1);
		global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchHun1]));
		w63.TopAttach = ((uint)(6));
		w63.BottomAttach = ((uint)(7));
		w63.XOptions = ((global::Gtk.AttachOptions)(4));
		w63.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchHun2 = new global::Gtk.Label();
		this.lblMarchHun2.Name = "lblMarchHun2";
		this.lblMarchHun2.Xalign = 0F;
		this.lblMarchHun2.LabelProp = global::Mono.Unix.Catalog.GetString("Jäger:");
		this.lblMarchHun2.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchHun2);
		global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchHun2]));
		w64.TopAttach = ((uint)(14));
		w64.BottomAttach = ((uint)(15));
		w64.XOptions = ((global::Gtk.AttachOptions)(4));
		w64.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchHun3 = new global::Gtk.Label();
		this.lblMarchHun3.Name = "lblMarchHun3";
		this.lblMarchHun3.Xalign = 0F;
		this.lblMarchHun3.LabelProp = global::Mono.Unix.Catalog.GetString("Jäger:");
		this.lblMarchHun3.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchHun3);
		global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchHun3]));
		w65.TopAttach = ((uint)(22));
		w65.BottomAttach = ((uint)(23));
		w65.XOptions = ((global::Gtk.AttachOptions)(4));
		w65.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchInf1 = new global::Gtk.Label();
		this.lblMarchInf1.Name = "lblMarchInf1";
		this.lblMarchInf1.Xalign = 0F;
		this.lblMarchInf1.LabelProp = global::Mono.Unix.Catalog.GetString("Infanterie:");
		this.lblMarchInf1.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchInf1);
		global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchInf1]));
		w66.TopAttach = ((uint)(4));
		w66.BottomAttach = ((uint)(5));
		w66.XOptions = ((global::Gtk.AttachOptions)(4));
		w66.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchInf2 = new global::Gtk.Label();
		this.lblMarchInf2.Name = "lblMarchInf2";
		this.lblMarchInf2.Xalign = 0F;
		this.lblMarchInf2.LabelProp = global::Mono.Unix.Catalog.GetString("Infanterie:");
		this.lblMarchInf2.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchInf2);
		global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchInf2]));
		w67.TopAttach = ((uint)(12));
		w67.BottomAttach = ((uint)(13));
		w67.XOptions = ((global::Gtk.AttachOptions)(4));
		w67.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchInf3 = new global::Gtk.Label();
		this.lblMarchInf3.Name = "lblMarchInf3";
		this.lblMarchInf3.Xalign = 0F;
		this.lblMarchInf3.LabelProp = global::Mono.Unix.Catalog.GetString("Infanterie:");
		this.lblMarchInf3.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchInf3);
		global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchInf3]));
		w68.TopAttach = ((uint)(20));
		w68.BottomAttach = ((uint)(21));
		w68.XOptions = ((global::Gtk.AttachOptions)(4));
		w68.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchPow1 = new global::Gtk.Label();
		this.lblMarchPow1.Name = "lblMarchPow1";
		this.lblMarchPow1.Xalign = 0F;
		this.lblMarchPow1.LabelProp = global::Mono.Unix.Catalog.GetString("Stärke:");
		this.lblMarchPow1.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchPow1);
		global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchPow1]));
		w69.TopAttach = ((uint)(1));
		w69.BottomAttach = ((uint)(2));
		w69.XOptions = ((global::Gtk.AttachOptions)(4));
		w69.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchPow2 = new global::Gtk.Label();
		this.lblMarchPow2.Name = "lblMarchPow2";
		this.lblMarchPow2.Xalign = 0F;
		this.lblMarchPow2.LabelProp = global::Mono.Unix.Catalog.GetString("Stärke:");
		this.lblMarchPow2.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchPow2);
		global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchPow2]));
		w70.TopAttach = ((uint)(9));
		w70.BottomAttach = ((uint)(10));
		w70.XOptions = ((global::Gtk.AttachOptions)(4));
		w70.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.lblMarchPow3 = new global::Gtk.Label();
		this.lblMarchPow3.Name = "lblMarchPow3";
		this.lblMarchPow3.Xalign = 0F;
		this.lblMarchPow3.LabelProp = global::Mono.Unix.Catalog.GetString("Stärke:");
		this.lblMarchPow3.Justify = ((global::Gtk.Justification)(1));
		this.layoutOutput.Add(this.lblMarchPow3);
		global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.lblMarchPow3]));
		w71.TopAttach = ((uint)(17));
		w71.BottomAttach = ((uint)(18));
		w71.XOptions = ((global::Gtk.AttachOptions)(4));
		w71.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchCapa1 = new global::Gtk.TextView();
		this.textMarchCapa1.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchCapa1.Sensitive = false;
		this.textMarchCapa1.Name = "textMarchCapa1";
		this.textMarchCapa1.Editable = false;
		this.textMarchCapa1.CursorVisible = false;
		this.textMarchCapa1.AcceptsTab = false;
		this.textMarchCapa1.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchCapa1);
		global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchCapa1]));
		w72.TopAttach = ((uint)(2));
		w72.BottomAttach = ((uint)(3));
		w72.LeftAttach = ((uint)(1));
		w72.RightAttach = ((uint)(2));
		w72.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchCapa2 = new global::Gtk.TextView();
		this.textMarchCapa2.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchCapa2.Sensitive = false;
		this.textMarchCapa2.Name = "textMarchCapa2";
		this.textMarchCapa2.Editable = false;
		this.textMarchCapa2.CursorVisible = false;
		this.textMarchCapa2.AcceptsTab = false;
		this.textMarchCapa2.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchCapa2);
		global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchCapa2]));
		w73.TopAttach = ((uint)(10));
		w73.BottomAttach = ((uint)(11));
		w73.LeftAttach = ((uint)(1));
		w73.RightAttach = ((uint)(2));
		w73.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchCapa3 = new global::Gtk.TextView();
		this.textMarchCapa3.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchCapa3.Sensitive = false;
		this.textMarchCapa3.Name = "textMarchCapa3";
		this.textMarchCapa3.Editable = false;
		this.textMarchCapa3.CursorVisible = false;
		this.textMarchCapa3.AcceptsTab = false;
		this.textMarchCapa3.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchCapa3);
		global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchCapa3]));
		w74.TopAttach = ((uint)(18));
		w74.BottomAttach = ((uint)(19));
		w74.LeftAttach = ((uint)(1));
		w74.RightAttach = ((uint)(2));
		w74.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchDriv1 = new global::Gtk.TextView();
		this.textMarchDriv1.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchDriv1.Sensitive = false;
		this.textMarchDriv1.Name = "textMarchDriv1";
		this.textMarchDriv1.Editable = false;
		this.textMarchDriv1.CursorVisible = false;
		this.textMarchDriv1.AcceptsTab = false;
		this.textMarchDriv1.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchDriv1);
		global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchDriv1]));
		w75.TopAttach = ((uint)(5));
		w75.BottomAttach = ((uint)(6));
		w75.LeftAttach = ((uint)(1));
		w75.RightAttach = ((uint)(2));
		w75.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchDriv2 = new global::Gtk.TextView();
		this.textMarchDriv2.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchDriv2.Sensitive = false;
		this.textMarchDriv2.Name = "textMarchDriv2";
		this.textMarchDriv2.Editable = false;
		this.textMarchDriv2.CursorVisible = false;
		this.textMarchDriv2.AcceptsTab = false;
		this.textMarchDriv2.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchDriv2);
		global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchDriv2]));
		w76.TopAttach = ((uint)(13));
		w76.BottomAttach = ((uint)(14));
		w76.LeftAttach = ((uint)(1));
		w76.RightAttach = ((uint)(2));
		w76.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchDriv3 = new global::Gtk.TextView();
		this.textMarchDriv3.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchDriv3.Sensitive = false;
		this.textMarchDriv3.Name = "textMarchDriv3";
		this.textMarchDriv3.Editable = false;
		this.textMarchDriv3.CursorVisible = false;
		this.textMarchDriv3.AcceptsTab = false;
		this.textMarchDriv3.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchDriv3);
		global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchDriv3]));
		w77.TopAttach = ((uint)(21));
		w77.BottomAttach = ((uint)(22));
		w77.LeftAttach = ((uint)(1));
		w77.RightAttach = ((uint)(2));
		w77.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchForm1 = new global::Gtk.TextView();
		this.textMarchForm1.Buffer.Text = global::Mono.Unix.Catalog.GetString("   /    /   ");
		this.textMarchForm1.Sensitive = false;
		this.textMarchForm1.Name = "textMarchForm1";
		this.textMarchForm1.Editable = false;
		this.textMarchForm1.CursorVisible = false;
		this.textMarchForm1.AcceptsTab = false;
		this.layoutOutput.Add(this.textMarchForm1);
		global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchForm1]));
		w78.TopAttach = ((uint)(3));
		w78.BottomAttach = ((uint)(4));
		w78.LeftAttach = ((uint)(1));
		w78.RightAttach = ((uint)(2));
		w78.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchForm2 = new global::Gtk.TextView();
		this.textMarchForm2.Buffer.Text = global::Mono.Unix.Catalog.GetString("   /    /   ");
		this.textMarchForm2.Sensitive = false;
		this.textMarchForm2.Name = "textMarchForm2";
		this.textMarchForm2.Editable = false;
		this.textMarchForm2.CursorVisible = false;
		this.textMarchForm2.AcceptsTab = false;
		this.layoutOutput.Add(this.textMarchForm2);
		global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchForm2]));
		w79.TopAttach = ((uint)(11));
		w79.BottomAttach = ((uint)(12));
		w79.LeftAttach = ((uint)(1));
		w79.RightAttach = ((uint)(2));
		w79.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchForm3 = new global::Gtk.TextView();
		this.textMarchForm3.Buffer.Text = global::Mono.Unix.Catalog.GetString("   /    /   ");
		this.textMarchForm3.Sensitive = false;
		this.textMarchForm3.Name = "textMarchForm3";
		this.textMarchForm3.Editable = false;
		this.textMarchForm3.CursorVisible = false;
		this.textMarchForm3.AcceptsTab = false;
		this.layoutOutput.Add(this.textMarchForm3);
		global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchForm3]));
		w80.TopAttach = ((uint)(19));
		w80.BottomAttach = ((uint)(20));
		w80.LeftAttach = ((uint)(1));
		w80.RightAttach = ((uint)(2));
		w80.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchHun1 = new global::Gtk.TextView();
		this.textMarchHun1.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchHun1.Sensitive = false;
		this.textMarchHun1.Name = "textMarchHun1";
		this.textMarchHun1.Editable = false;
		this.textMarchHun1.CursorVisible = false;
		this.textMarchHun1.AcceptsTab = false;
		this.textMarchHun1.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchHun1);
		global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchHun1]));
		w81.TopAttach = ((uint)(6));
		w81.BottomAttach = ((uint)(7));
		w81.LeftAttach = ((uint)(1));
		w81.RightAttach = ((uint)(2));
		w81.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchHun2 = new global::Gtk.TextView();
		this.textMarchHun2.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchHun2.Sensitive = false;
		this.textMarchHun2.Name = "textMarchHun2";
		this.textMarchHun2.Editable = false;
		this.textMarchHun2.CursorVisible = false;
		this.textMarchHun2.AcceptsTab = false;
		this.textMarchHun2.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchHun2);
		global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchHun2]));
		w82.TopAttach = ((uint)(14));
		w82.BottomAttach = ((uint)(15));
		w82.LeftAttach = ((uint)(1));
		w82.RightAttach = ((uint)(2));
		w82.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchHun3 = new global::Gtk.TextView();
		this.textMarchHun3.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchHun3.Sensitive = false;
		this.textMarchHun3.Name = "textMarchHun3";
		this.textMarchHun3.Editable = false;
		this.textMarchHun3.CursorVisible = false;
		this.textMarchHun3.AcceptsTab = false;
		this.textMarchHun3.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchHun3);
		global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchHun3]));
		w83.TopAttach = ((uint)(22));
		w83.BottomAttach = ((uint)(23));
		w83.LeftAttach = ((uint)(1));
		w83.RightAttach = ((uint)(2));
		w83.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchInf1 = new global::Gtk.TextView();
		this.textMarchInf1.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchInf1.Sensitive = false;
		this.textMarchInf1.Name = "textMarchInf1";
		this.textMarchInf1.Editable = false;
		this.textMarchInf1.CursorVisible = false;
		this.textMarchInf1.AcceptsTab = false;
		this.textMarchInf1.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchInf1);
		global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchInf1]));
		w84.TopAttach = ((uint)(4));
		w84.BottomAttach = ((uint)(5));
		w84.LeftAttach = ((uint)(1));
		w84.RightAttach = ((uint)(2));
		w84.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchInf2 = new global::Gtk.TextView();
		this.textMarchInf2.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchInf2.Sensitive = false;
		this.textMarchInf2.Name = "textMarchInf2";
		this.textMarchInf2.Editable = false;
		this.textMarchInf2.CursorVisible = false;
		this.textMarchInf2.AcceptsTab = false;
		this.textMarchInf2.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchInf2);
		global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchInf2]));
		w85.TopAttach = ((uint)(12));
		w85.BottomAttach = ((uint)(13));
		w85.LeftAttach = ((uint)(1));
		w85.RightAttach = ((uint)(2));
		w85.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchInf3 = new global::Gtk.TextView();
		this.textMarchInf3.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchInf3.Sensitive = false;
		this.textMarchInf3.Name = "textMarchInf3";
		this.textMarchInf3.Editable = false;
		this.textMarchInf3.CursorVisible = false;
		this.textMarchInf3.AcceptsTab = false;
		this.textMarchInf3.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchInf3);
		global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchInf3]));
		w86.TopAttach = ((uint)(20));
		w86.BottomAttach = ((uint)(21));
		w86.LeftAttach = ((uint)(1));
		w86.RightAttach = ((uint)(2));
		w86.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchPow1 = new global::Gtk.TextView();
		this.textMarchPow1.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchPow1.Sensitive = false;
		this.textMarchPow1.Name = "textMarchPow1";
		this.textMarchPow1.Editable = false;
		this.textMarchPow1.CursorVisible = false;
		this.textMarchPow1.AcceptsTab = false;
		this.textMarchPow1.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchPow1);
		global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchPow1]));
		w87.TopAttach = ((uint)(1));
		w87.BottomAttach = ((uint)(2));
		w87.LeftAttach = ((uint)(1));
		w87.RightAttach = ((uint)(2));
		w87.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchPow2 = new global::Gtk.TextView();
		this.textMarchPow2.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchPow2.Sensitive = false;
		this.textMarchPow2.Name = "textMarchPow2";
		this.textMarchPow2.Editable = false;
		this.textMarchPow2.CursorVisible = false;
		this.textMarchPow2.AcceptsTab = false;
		this.textMarchPow2.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchPow2);
		global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchPow2]));
		w88.TopAttach = ((uint)(9));
		w88.BottomAttach = ((uint)(10));
		w88.LeftAttach = ((uint)(1));
		w88.RightAttach = ((uint)(2));
		w88.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child layoutOutput.Gtk.Table+TableChild
		this.textMarchPow3 = new global::Gtk.TextView();
		this.textMarchPow3.Buffer.Text = global::Mono.Unix.Catalog.GetString("0");
		this.textMarchPow3.Sensitive = false;
		this.textMarchPow3.Name = "textMarchPow3";
		this.textMarchPow3.Editable = false;
		this.textMarchPow3.CursorVisible = false;
		this.textMarchPow3.AcceptsTab = false;
		this.textMarchPow3.Justification = ((global::Gtk.Justification)(2));
		this.layoutOutput.Add(this.textMarchPow3);
		global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.layoutOutput[this.textMarchPow3]));
		w89.TopAttach = ((uint)(17));
		w89.BottomAttach = ((uint)(18));
		w89.LeftAttach = ((uint)(1));
		w89.RightAttach = ((uint)(2));
		w89.YOptions = ((global::Gtk.AttachOptions)(4));
		this.layoutInput_Output.Add(this.layoutOutput);
		global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.layoutInput_Output[this.layoutOutput]));
		w90.Position = 2;
		this.layoutMenu_Input_Button.Add(this.layoutInput_Output);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.layoutMenu_Input_Button[this.layoutInput_Output]));
		w91.Position = 1;
		this.Add(this.layoutMenu_Input_Button);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 621;
		this.DefaultHeight = 535;
		this.buttonTroopsSave.Hide();
		this.lblMissingTroops.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.cbxInfantryTroops.Changed += new global::System.EventHandler(this.OnCbxInfantryTroopsChanged);
		this.cbxHunterTroops.Changed += new global::System.EventHandler(this.OnCbxHunterTroopsChanged);
		this.cbxDriverTroops.Changed += new global::System.EventHandler(this.OnCbxDriverTroopsChanged);
		this.rbnMarch1.Pressed += new global::System.EventHandler(this.OnRbnMarch1Pressed);
		this.rbnMarch2.Pressed += new global::System.EventHandler(this.OnRbnMarch2Pressed);
		this.rbnMarch3.Pressed += new global::System.EventHandler(this.OnRbnMarch3Pressed);
		this.buttonNextMarch.Clicked += new global::System.EventHandler(this.OnButtonNextMarchClicked);
		this.buttonReset.Clicked += new global::System.EventHandler(this.OnButtonResetClicked);
	}
}
